# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "The Epistemic Diary"
baseURL = "https://trandung6129.github.io/"
theme = [
  "FixIt",
  "shortcode-docs-bookmark"
]
defaultContentLanguage = "vi"
languageCode = "vi"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 70
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
