[vi]
  languageName = "Tiếng Việt"
  weight = 1
  [vi.params]
    description = "Cái gì tôi sợ quên thì tôi note lại ở đây."
    [vi.params.home]
      subtitle = "Cái gì tôi sợ quên thì tôi note lại ở đây."

[en]
  languageName = "English"
  weight = 2
  [en.params]
    description = "A Clean, Elegant but Advanced Hugo Theme"
    [en.params.home]
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"

[ja]
  languageName = "日本語"
  weight = 3
  [ja.params]
    description = "クリーンでエレガント、そして先進的な Hugo テーマ"
    [ja.params.home]
      subtitle = "クリーンでエレガント、そして先進的な Hugo テーマ"

[zh-cn]
  languageName = "简体中文"
  weight = 4
  [zh-cn.params]
    description = "一个简洁、优雅且功能强大的 Hugo 主题"
    [zh-cn.params.home]
      subtitle = "一个简洁、优雅且功能强大的 Hugo 主题"
